Fix naming of configuration parameters, add support for keycloak
rciam/simplesamlphp-module-rciamauthorize pull request #6
Opened 2022-05-31 05:50 UTC by lionick

2022-05-31 08:34 UTC, NicolasLiampotis requested changes

2022-05-31 08:34 UTC, NicolasLiampotis commented on lib/Auth/Process/OIDCAuthorize.php
> +      && strpos($request['Destination']['entityid'],
Exact match. Test with https://{{ rciam_hostname }}/auth/realms/egi

2022-06-01 07:28 UTC, NicolasLiampotis requested changes

2022-06-01 07:28 UTC, NicolasLiampotis commented on lib/Auth/Process/OIDCAuthorize.php
> +      $client_id = explode('.', $request['saml:RelayState'], 3)[2];
We should log error "[OIDCAuthorize] Client ID is empty" and throw an UNHANDLEDEXCEPTION 'Oops something went wrong' error if the client_id is empty

2022-06-02 06:56 UTC, lionick commented on lib/Auth/Process/OIDCAuthorize.php
> +      $client_id = explode('.', $request['saml:RelayState'], 3)[2];
I have just added an UNHANDLEDEXCEPTION with a meaningful message as this is only printed at logs. User sees a screen with the tracking number of the error.

2022-06-02 08:23 UTC, NicolasLiampotis approved these changes
LGTM

2022-06-02 08:23 UTC, merged